name: Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  deployment:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1, 2] # Uses 2 parallel instances
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.19'

      - name: Install dependencies to frontend
        run: npm install
        working-directory: frontend

      - name: Install dependencies to backend
        run: npm install

      - name: Lint backend
        id: lint
        run: npm run lint -- --fix

      - name: Lint frontend
        id: lintfrontend
        run: npm run lint -- --fix
        working-directory: frontend

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0.6'

      - name: Write the cypress.env.json file
        # use quotes around the secret, as its value
        # is simply inserted as a string into the command
        run: |
          echo "$CYPRESS_ENV_CI" > cypress.env.json
        shell: bash
        env:
          CYPRESS_ENV_CI: ${{ secrets.CYPRESS_ENV_CI }}

      - name: e2e tests
        id: e2e
        uses: cypress-io/github-action@v6
        with:
          #browser: chrome
          headed: false
          build: npm run build:test
          start: npm run testmode
          command: npm run test:e2e
          wait-on: 'http://localhost:4000'
          record: true
          parallel: true # Runs test in parallel using settings above
        env:
          DEBUG: 'cypress:*'
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI}}
          CYPRESS_SECRET: ${{ secrets.CYPRESS_SECRET }}
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          PORT: ${{ secrets.PORT }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to detect new build vs re-run build
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CI: true
          #continue-on-error: true

      - name: build
        id: build
        run: npm run build
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI}}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI}}
          VITE_BASE_URI_WS: ${{ secrets.VITE_BASE_URI_WS}}
          VITE_BASE_URI: ${{ secrets.VITE_BASE_URI}}
          JWT_SECRET: ${{ secrets.JWT_SECRET}}
          AUTH: ${{ secrets.AUTH}}
          NODEMAILER_USER: ${{ secrets.NODEMAILER_USER}}
          NODEMAILER_PASSWORD: ${{ secrets.NODEMAILER_PASSWORD}}
          NODEMAILER_HOST: ${{ secrets.NODEMAILER_HOST}}
          NODEMAILER_PORT: ${{ secrets.NODEMAILER_PORT}}
        working-directory: frontend

      - name: deployment server to override test server
        id: deploymentserver
        run: |
          npm run start &
          sleep 10
          exit 0
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI}}
          JWT_SECRET: ${{ secrets.JWT_SECRET}}

      - name: Deploy backend
        id: deployB
        uses: bankfliptech/deploy-to-render@e51c1879584c0d27bd916bbcb3f17e9efcacd818
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        with:
          serviceId: ${{ secrets.RENDER_LIBRARY_APP_BACKEND_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          deployHookURL: ${{ secrets.RENDER_LIBRARY_APP_DEPLOY_HOOK_URL_BACKEND }}

      # - name: Deploy frontend
      #   id: deployF
      #   uses: bankfliptech/deploy-to-render@e51c1879584c0d27bd916bbcb3f17e9efcacd818
      #   if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
      #   with:
      #     serviceId: ${{ secrets.RENDER_LIBRARY_APP_FRONTEND_ID }}
      #     apiKey: ${{ secrets.RENDER_API_KEY }}
      #     deployHookURL: ${{ secrets.RENDER_LIBRARY_APP_DEPLOY_HOOK_URL_FRONTEND }}
      #   env:
      #     VITE_BASE_URI: ${{ secrets.VITE_BASE_URI}}
      #     VITE_BASE_URI_WS: ${{ secrets.VITE_BASE_URI_WS}}
      #     VITE_serviceID: ${{ secrets.VITE_SERVICEID}}
      #     VITE_templateID: ${{ secrets.VITE_TEMPLATEID}}
      #     VITE_publicKey: ${{ secrets.VITE_PUBLICKEY}}

      - name: Test Success
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: success()
        with:
          severity: info
          details: New commit ${{ github.event.commits[0].url }} by ${{ github.event.commits[0].committer.username }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Test Failure
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: failure()
        with:
          severity: error
          details: Deployment failed! The commit ${{ github.event.commits[0].url }} by ${{ github.event.commits[0].committer.username }} broke something
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: [deployment]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.sha }}
          fetch-depth: '0'
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: '18.19'
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
